# Generated by Django 5.2 on 2025-04-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('repeticoes', models.IntegerField()),
                ('series', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichadetreinos.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichadetreinos.professor')),
            ],
        ),
    ]
