# Generated by Django 5.2 on 2025-04-30 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichadetreinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('grupo_muscular', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='treino',
            name='grupo_muscular',
        ),
        migrations.AddField(
            model_name='treino',
            name='ordem',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treino',
            name='exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fichadetreinos.exercicio'),
        ),
    ]
